# 作業

思考一下我們前面有提到圖片是矩陣，但維度可能會不一樣
例如灰階圖只有兩個維度，RGB 彩圖則有 3 個維度

假如今天我們把 RGB 3 個維度拆開來看會有甚麼不同的效果呢？

In [39]:
import cv2
import numpy as np

img_path = 'lena.png'

# 以彩色圖片的方式載入
img = cv2.imread(img_path, cv2.IMREAD_COLOR)
img_BGR=cv2.imread(img_path)



B,G,R=cv2.split(img_BGR)
img_BGR=cv2.merge((B,G,R))

R=img_BGR[:,:,0]=R*255
G=img_BGR[:,:,1]=G*255
B=img_BGR[:,:,2]=B*255


print(R)
print(G)
print(B)
# img_red.setcolor(0,0,255)
# 以灰階圖片的方式載入
img_gray = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)

# 為了要不斷顯示圖片，所以使用一個迴圈
while True:
    # 顯示彩圖
    cv2.imshow('bgr', img)
    # 顯示灰圖
    cv2.imshow('gray', img_gray)
    
    cv2.imshow('blue',B)
    
    cv2.imshow('red',R)
    
    cv2.imshow('green',G)

    # 直到按下 ESC 鍵才會自動關閉視窗結束程式
    k = cv2.waitKey(0)
    if k == 27:
        cv2.destroyAllWindows()
        break

[[ 30  30  33 ...  26  35  56]
 [ 30  30  33 ...  26  35  56]
 [ 30  30  33 ...  26  35  56]
 ...
 [172 172 164 ...  83  84  79]
 [174 174 160 ...  77  75  71]
 [174 174 160 ...  77  75  71]]
[[119 119 119 ... 108 126 157]
 [119 119 119 ... 108 126 157]
 [119 119 119 ... 108 126 157]
 ...
 [238 238 229 ... 183 188 194]
 [234 234 224 ... 186 185 182]
 [234 234 224 ... 186 185 182]]
[[131 131 123 ... 134 146 166]
 [131 131 123 ... 134 146 166]
 [131 131 123 ... 134 146 166]
 ...
 [196 196 198 ... 172 180 177]
 [199 199 194 ... 177 175 175]
 [199 199 194 ... 177 175 175]]
